import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import data from '../data/data.json'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> Admin Dashboard Engine
        </h1>

        <p className={styles.description}>This dashboard admin engine makes it easy for all your freelance clients to easily edit page content in your next.js apps and only takes a few minutest to set up!  Be sure to check out the <a href="https://github.com/Conner1115/next-admi">github repo</a> for instructions to add it to your app.</p>

        <p className={styles.description}>Feel free to edit all the content on the <Link href="/playground">Playground Page</Link>, but please keep it clean.</p>

        <p className={styles.description}>Log into the <Link href="/admin">Administration Dashboard</Link> with password <code>strongpassword123</code></p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

